import { SYSTEM_IDS } from './_constants';
import type { KPIReconciliation } from '../../types/kpi';

export const KPI_RECONCILIATIONS: KPIReconciliation[] = [
  {
    kpiId: 'kpi-denial-rate',
    kpiName: 'Denial Rate',
    category: 'revenue',
    canonicalDefinition: 'All denied claims (initial + appeal) / total claims submitted, measured at ERA receipt date',
    definitionVariants: [
      {
        systemId: SYSTEM_IDS.EPIC,
        systemName: 'Summit Flagship Orthopedics',
        definitionText: 'Initial denials only; excludes partial denials and appeals. Counted at claim submission date.',
        sourceFields: ['claims.denial_flag', 'claims.submission_date'],
        valueUnderLocal: 5.1,
        valueUnderCanonical: 11.2,
      },
      {
        systemId: SYSTEM_IDS.ATHENA,
        systemName: 'Peak Performance Sports Medicine',
        definitionText: 'Includes initial + partial denials. Counts at posting date, not submission date.',
        sourceFields: ['billing.denial_status', 'billing.posting_date'],
        valueUnderLocal: 8.7,
        valueUnderCanonical: 11.4,
      },
      {
        systemId: SYSTEM_IDS.MODMED,
        systemName: 'Alpine Joint & Spine Center',
        definitionText: 'All denials including resubmissions counted as new claims. Inflates both numerator and denominator.',
        sourceFields: ['rcm.claim_status', 'rcm.denial_code', 'rcm.resubmit_flag'],
        valueUnderLocal: 12.3,
        valueUnderCanonical: 11.7,
      },
    ],
    downstreamCascade: [
      {
        type: 'exhibit',
        label: 'QoE Exhibit — Revenue Adjustments',
        previousState: '5.1% (Epic flagship only)',
        newState: '11.7% (unified across 20 locations)',
        detail: 'Understated denial rate masked $1.2M in recoverable revenue',
      },
      {
        type: 'risk-flag',
        label: 'Operational Risk — Denial Management',
        previousState: 'Low risk (flagship metric)',
        newState: 'Medium risk (platform-wide)',
      },
      {
        type: 'integration-baseline',
        label: 'Denial Rate Baseline',
        previousState: 'Not established',
        newState: '11.7% — target: 7.5% within 12 months',
      },
    ],
    dollarImpact: { amount: 1_200_000, description: 'Undercounted denials across non-flagship practices represent $1.2M in potentially recoverable revenue through improved denial management' },
    integrationBaseline: { value: 11.7, label: '11.7% platform-wide denial rate' },
  },
  {
    kpiId: 'kpi-net-collection',
    kpiName: 'Net Collection Rate',
    category: 'revenue',
    canonicalDefinition: 'Total collections / (total charges − contractual adjustments), measured on ERA receipt date with 90-day lookback',
    definitionVariants: [
      {
        systemId: SYSTEM_IDS.EPIC,
        systemName: 'Summit Flagship Orthopedics',
        definitionText: 'Collections / net charges using ERA receipt date. Includes all adjustment categories.',
        sourceFields: ['billing.collections', 'billing.charges', 'billing.adjustments', 'billing.era_date'],
        valueUnderLocal: 96.1,
        valueUnderCanonical: 91.8,
      },
      {
        systemId: SYSTEM_IDS.ATHENA,
        systemName: 'Peak Performance Sports Medicine',
        definitionText: 'Uses posting date instead of ERA receipt date. 30-day lookback window understates aged collections.',
        sourceFields: ['payments.amount', 'charges.total', 'adjustments.contractual'],
        valueUnderLocal: 93.4,
        valueUnderCanonical: 91.2,
      },
      {
        systemId: SYSTEM_IDS.ECW,
        systemName: 'Ridgeline Orthopedic Associates',
        definitionText: 'Excludes bad debt write-offs from denominator, artificially inflating the rate.',
        sourceFields: ['ar.payments', 'ar.charges', 'ar.writeoffs'],
        valueUnderLocal: 97.8,
        valueUnderCanonical: 89.3,
      },
    ],
    downstreamCascade: [
      {
        type: 'exhibit',
        label: 'QoE Exhibit — Collection Efficiency',
        previousState: '96.1% (flagship reporting)',
        newState: '91.8% (unified, 90-day lookback)',
        detail: 'eCW practices were overstating NCR by 8.5 points due to bad debt exclusion',
      },
      {
        type: 'risk-flag',
        label: 'Revenue Leakage — Aged AR',
        previousState: 'Not flagged',
        newState: 'High risk ($1.8M estimated leakage)',
      },
    ],
    dollarImpact: { amount: 1_800_000, description: 'Inconsistent collection measurement across practices obscures $1.8M in revenue leakage, primarily from eCW practices excluding bad debt and Athenahealth\'s short lookback window' },
    integrationBaseline: { value: 91.8, label: '91.8% unified net collection rate' },
  },
  {
    kpiId: 'kpi-clean-claim',
    kpiName: 'Clean Claim Rate',
    category: 'operational',
    canonicalDefinition: 'Claims accepted on first submission with zero edits, rejections, or soft-edit overrides / total claims submitted',
    definitionVariants: [
      {
        systemId: SYSTEM_IDS.EPIC,
        systemName: 'Summit Flagship Orthopedics',
        definitionText: 'First-submission acceptance rate. Includes soft-edit overrides as "clean" if no hard rejection.',
        sourceFields: ['claims.first_pass_flag', 'claims.edit_count'],
        valueUnderLocal: 92.7,
        valueUnderCanonical: 88.4,
      },
      {
        systemId: SYSTEM_IDS.MODMED,
        systemName: 'Alpine Joint & Spine Center',
        definitionText: 'Counts all claims that eventually clear without human review, including those with automated soft-edit overrides.',
        sourceFields: ['rcm.clean_flag', 'rcm.override_log'],
        valueUnderLocal: 91.2,
        valueUnderCanonical: 86.9,
      },
      {
        systemId: SYSTEM_IDS.WEBPT,
        systemName: 'Summit PT & Rehabilitation',
        definitionText: 'PT claims only. Different CPT mix (97110, 97140) means inherently higher clean rates for therapy vs. surgical claims.',
        sourceFields: ['billing.claim_status', 'billing.cpt_code'],
        valueUnderLocal: 96.4,
        valueUnderCanonical: 95.1,
      },
    ],
    downstreamCascade: [
      {
        type: 'exhibit',
        label: 'QoE Exhibit — RCM Efficiency',
        previousState: '92.7% (soft-edit overrides counted as clean)',
        newState: '88.4% (strict first-pass, no overrides)',
      },
      {
        type: 'integration-baseline',
        label: 'Clean Claim Baseline',
        previousState: 'Not established',
        newState: '88.4% — target: 95% with unified coding rules',
      },
    ],
    dollarImpact: { amount: 620_000, description: 'Soft-edit override inflation masks rework costs of $620K annually in staff time and delayed reimbursement' },
    integrationBaseline: { value: 88.4, label: '88.4% strict clean claim rate' },
  },
  {
    kpiId: 'kpi-cost-per-claim',
    kpiName: 'Cost per Claim',
    category: 'cost',
    canonicalDefinition: 'Fully-loaded RCM cost (labor + vendor fees + technology) / total claims submitted per month',
    definitionVariants: [
      {
        systemId: SYSTEM_IDS.ATHENA,
        systemName: 'Peak Performance Sports Medicine',
        definitionText: 'Direct labor cost only. Excludes vendor clearinghouse fees and technology licensing.',
        sourceFields: ['rcm.labor_cost', 'rcm.claim_volume'],
        valueUnderLocal: 6.80,
        valueUnderCanonical: 8.45,
      },
      {
        systemId: SYSTEM_IDS.EPIC,
        systemName: 'Summit Flagship Orthopedics',
        definitionText: 'Includes direct labor and vendor fees. Technology cost allocated but not at claim level.',
        sourceFields: ['finance.rcm_cost', 'finance.vendor_fees', 'claims.monthly_volume'],
        valueUnderLocal: 8.20,
        valueUnderCanonical: 8.95,
      },
      {
        systemId: SYSTEM_IDS.ECW,
        systemName: 'Ridgeline Orthopedic Associates',
        definitionText: 'Per-claim cost not tracked. Only aggregate monthly RCM spend available.',
        sourceFields: ['gl.rcm_expense'],
        valueUnderLocal: 0,
        valueUnderCanonical: 9.20,
      },
    ],
    downstreamCascade: [
      {
        type: 'risk-flag',
        label: 'Cost Variance — RCM Operations',
        previousState: '$6.80 (labor-only reporting)',
        newState: '$8.45 (fully-loaded, platform-wide)',
        detail: 'eCW practices had no per-claim tracking, making cost benchmarking impossible',
      },
      {
        type: 'exhibit',
        label: 'QoE Exhibit — Operating Cost Analysis',
        previousState: 'Incomplete (2 of 3 practice groups)',
        newState: 'Complete ($8.45 weighted average)',
      },
      {
        type: 'integration-baseline',
        label: 'Cost per Claim Baseline',
        previousState: 'Not established',
        newState: '$8.45 — target: $7.00 via RCM consolidation',
      },
    ],
    dollarImpact: { amount: 950_000, description: 'Understated claim costs hide $950K in RCM inefficiency across smaller practices, particularly eCW sites with no per-claim cost tracking' },
    integrationBaseline: { value: 8.45, label: '$8.45 fully-loaded cost per claim' },
  },
  {
    kpiId: 'kpi-provider-utilization',
    kpiName: 'Provider Utilization',
    category: 'operational',
    canonicalDefinition: 'Work RVUs (wRVUs) per provider FTE per month, normalized to orthopedic specialty mix',
    definitionVariants: [
      {
        systemId: SYSTEM_IDS.EPIC,
        systemName: 'Summit Flagship Orthopedics',
        definitionText: 'wRVUs per FTE per month. Orthopedic-specific RVU schedule. Gold standard measurement.',
        sourceFields: ['productivity.wrvus', 'providers.fte_status', 'providers.specialty'],
        valueUnderLocal: 425,
        valueUnderCanonical: 425,
      },
      {
        systemId: SYSTEM_IDS.ATHENA,
        systemName: 'Peak Performance Sports Medicine',
        definitionText: 'Appointment slot fill rate (%). Not convertible to wRVUs without CPT-level procedure data.',
        sourceFields: ['scheduling.slots_available', 'scheduling.slots_filled'],
        valueUnderLocal: 87,
        valueUnderCanonical: 382,
      },
      {
        systemId: SYSTEM_IDS.WEBPT,
        systemName: 'Summit PT & Rehabilitation',
        definitionText: 'Patient visits per therapist per day. PT-specific metric, incompatible units with surgical wRVUs.',
        sourceFields: ['schedule.daily_visits', 'staff.therapist_count'],
        valueUnderLocal: 12,
        valueUnderCanonical: 298,
      },
    ],
    downstreamCascade: [
      {
        type: 'exhibit',
        label: 'QoE Exhibit — Provider Productivity',
        previousState: '3 incompatible metrics across systems',
        newState: '382 wRVU/FTE/month (unified, weighted)',
        detail: 'Athena sites reporting 87% slot fill obscured below-benchmark wRVU output',
      },
      {
        type: 'risk-flag',
        label: 'Productivity Gap — Mid-size Practices',
        previousState: 'Not measurable (incompatible units)',
        newState: '382 vs. 425 wRVU gap (10% below flagship)',
      },
      {
        type: 'integration-baseline',
        label: 'Provider Utilization Baseline',
        previousState: 'Not established',
        newState: '382 wRVU/FTE/month — target: 420 within 12 months',
      },
    ],
    dollarImpact: { amount: 2_100_000, description: 'Incompatible utilization metrics across 3 measurement systems prevented identification of a $2.1M productivity gap in mid-size and PT practices' },
    integrationBaseline: { value: 382, label: '382 wRVU/FTE/month platform-wide' },
  },
];
