import type { ModelProject, ModelFeature } from '../../types/model';
import { MODEL_COUNTS } from './_constants';

export const MODEL_FEATURES: ModelFeature[] = [
  // ── Pre-op ──
  {
    id: 'patient_age',
    name: 'Patient Age at Surgery',
    category: 'pre-op',
    sources: ['Epic', 'athenahealth', 'Modernizing Medicine'],
    coverageSites: '20/20 sites',
    coverageCases: '100% of cases',
    mappingConfidence: 99,
    confidenceLevel: 'high',
    literatureCitations: [
      {
        title: 'Age as a predictor of 30-day morbidity after total knee arthroplasty',
        source: 'Journal of Arthroplasty',
        year: 2021,
        relevanceScore: 0.95,
      },
      {
        title: 'Risk factors for complications following primary TKA: a national database analysis',
        source: 'Clinical Orthopaedics and Related Research',
        year: 2020,
        relevanceScore: 0.88,
      },
    ],
    included: true,
  },
  {
    id: 'bmi',
    name: 'Body Mass Index',
    category: 'pre-op',
    sources: ['Epic', 'athenahealth', 'WebPT'],
    coverageSites: '19/20 sites',
    coverageCases: '96% of cases',
    mappingConfidence: 97,
    confidenceLevel: 'high',
    literatureCitations: [
      {
        title: 'Obesity and outcomes after total knee arthroplasty: a systematic review',
        source: 'Journal of Bone and Joint Surgery',
        year: 2022,
        relevanceScore: 0.93,
      },
      {
        title: 'BMI thresholds and perioperative complications in TKA',
        source: 'The Knee',
        year: 2021,
        relevanceScore: 0.87,
      },
    ],
    included: true,
    normalizationNote: 'Height/weight converted to BMI where raw BMI unavailable; 3 sites report in metric units',
  },
  {
    id: 'hba1c',
    name: 'HbA1c (Most Recent Pre-op)',
    category: 'pre-op',
    sources: ['Epic', 'athenahealth', 'eClinicalWorks', 'Pharmacy Feed'],
    coverageSites: '16/20 sites',
    coverageCases: '82% of cases',
    mappingConfidence: 88,
    confidenceLevel: 'medium',
    literatureCitations: [
      {
        title: 'Perioperative glycemic control and surgical site infection after TKA',
        source: 'Journal of Arthroplasty',
        year: 2023,
        relevanceScore: 0.91,
      },
      {
        title: 'HbA1c cutoffs for elective total joint arthroplasty: a meta-analysis',
        source: 'Archives of Orthopaedic and Trauma Surgery',
        year: 2022,
        relevanceScore: 0.85,
      },
      {
        title: 'Diabetes management and outcomes in orthopedic surgery',
        source: 'Clinical Orthopaedics and Related Research',
        year: 2020,
        relevanceScore: 0.80,
      },
    ],
    included: true,
    normalizationNote: '4 sites report as percentage, 12 sites as mmol/mol; normalized to percentage',
  },
  {
    id: 'pre_op_lefs',
    name: 'Pre-op LEFS Score',
    category: 'pre-op',
    sources: ['Epic', 'WebPT', 'Modernizing Medicine'],
    coverageSites: '18/20 sites',
    coverageCases: '91% of cases',
    mappingConfidence: 94,
    confidenceLevel: 'high',
    literatureCitations: [
      {
        title: 'Lower Extremity Functional Scale as a predictor of post-TKA outcomes',
        source: 'Physical Therapy',
        year: 2021,
        relevanceScore: 0.89,
      },
      {
        title: 'Pre-operative functional status and complication risk in total knee replacement',
        source: 'Knee Surgery, Sports Traumatology, Arthroscopy',
        year: 2022,
        relevanceScore: 0.84,
      },
    ],
    included: true,
    normalizationNote: 'LEFS 0-80 scale; 2 sites use KOOS-JR converted via published crosswalk',
  },
  {
    id: 'smoking_history',
    name: 'Smoking History',
    category: 'pre-op',
    sources: ['Epic', 'athenahealth', 'eClinicalWorks'],
    coverageSites: '17/20 sites',
    coverageCases: '87% of cases',
    mappingConfidence: 85,
    confidenceLevel: 'medium',
    literatureCitations: [
      {
        title: 'Smoking and complications after total knee arthroplasty: a propensity-matched analysis',
        source: 'Journal of Arthroplasty',
        year: 2022,
        relevanceScore: 0.90,
      },
      {
        title: 'Current smoking status and surgical outcomes in orthopedic patients',
        source: 'Orthopedics',
        year: 2021,
        relevanceScore: 0.82,
      },
    ],
    included: true,
    normalizationNote: 'Mapped to ordinal: 0 = never, 1 = former, 2 = current; free-text entries NLP-parsed',
  },

  // ── Procedure ──
  {
    id: 'surgical_duration_min',
    name: 'Surgical Duration (minutes)',
    category: 'procedure',
    sources: ['Epic', 'athenahealth', 'Modernizing Medicine'],
    coverageSites: '20/20 sites',
    coverageCases: '100% of cases',
    mappingConfidence: 98,
    confidenceLevel: 'high',
    literatureCitations: [
      {
        title: 'Operative time as an independent risk factor for complications after TKA',
        source: 'Journal of Bone and Joint Surgery',
        year: 2021,
        relevanceScore: 0.92,
      },
    ],
    included: true,
  },
  {
    id: 'anesthesia_type',
    name: 'Anesthesia Type',
    category: 'procedure',
    sources: ['Epic', 'athenahealth'],
    coverageSites: '20/20 sites',
    coverageCases: '99% of cases',
    mappingConfidence: 96,
    confidenceLevel: 'high',
    literatureCitations: [
      {
        title: 'Regional versus general anesthesia for total knee arthroplasty: complication rates',
        source: 'Anesthesiology',
        year: 2022,
        relevanceScore: 0.88,
      },
      {
        title: 'Neuraxial anesthesia and 30-day outcomes after lower extremity arthroplasty',
        source: 'Regional Anesthesia and Pain Medicine',
        year: 2021,
        relevanceScore: 0.85,
      },
    ],
    included: true,
    normalizationNote: 'Mapped to categorical: general, spinal, epidural, regional-block',
  },
  {
    id: 'implant_manufacturer',
    name: 'Implant Manufacturer',
    category: 'procedure',
    sources: ['Epic', 'Modernizing Medicine', 'Radiology PACS'],
    coverageSites: '15/20 sites',
    coverageCases: '78% of cases',
    mappingConfidence: 82,
    confidenceLevel: 'medium',
    literatureCitations: [
      {
        title: 'Implant design and early failure rates in total knee arthroplasty: a registry study',
        source: 'Journal of Arthroplasty',
        year: 2023,
        relevanceScore: 0.86,
      },
    ],
    included: true,
    normalizationNote: 'Manufacturer names normalized against FDA 510(k) database; 5 sites use free-text OR notes',
  },
  {
    id: 'tourniquet_time_min',
    name: 'Tourniquet Time (minutes)',
    category: 'procedure',
    sources: ['Epic', 'athenahealth'],
    coverageSites: '19/20 sites',
    coverageCases: '95% of cases',
    mappingConfidence: 93,
    confidenceLevel: 'high',
    literatureCitations: [
      {
        title: 'Tourniquet use and complications in total knee arthroplasty',
        source: 'Knee Surgery, Sports Traumatology, Arthroscopy',
        year: 2022,
        relevanceScore: 0.87,
      },
      {
        title: 'Prolonged tourniquet time and venous thromboembolism risk after TKA',
        source: 'Journal of Arthroplasty',
        year: 2021,
        relevanceScore: 0.83,
      },
    ],
    included: true,
  },

  // ── Post-op Biometric ──
  {
    id: 'temp_day3_deviation',
    name: 'Temperature Deviation (Post-op Day 3)',
    category: 'post-op-biometric',
    sources: ['Epic', 'athenahealth', 'WebPT'],
    coverageSites: '18/20 sites',
    coverageCases: '90% of cases',
    mappingConfidence: 91,
    confidenceLevel: 'high',
    literatureCitations: [
      {
        title: 'Post-operative fever and infection risk after total joint arthroplasty',
        source: 'Journal of Arthroplasty',
        year: 2022,
        relevanceScore: 0.90,
      },
      {
        title: 'Temperature monitoring in the post-TKA period: predictive value for complications',
        source: 'Archives of Orthopaedic and Trauma Surgery',
        year: 2023,
        relevanceScore: 0.84,
      },
    ],
    included: true,
    normalizationNote: 'Expressed as deviation from 37.0°C baseline; Fahrenheit sources converted',
  },
  {
    id: 'hr_baseline_shift_day5',
    name: 'Heart Rate Baseline Shift (Post-op Day 5)',
    category: 'post-op-biometric',
    sources: ['Epic', 'athenahealth'],
    coverageSites: '14/20 sites',
    coverageCases: '72% of cases',
    mappingConfidence: 84,
    confidenceLevel: 'medium',
    literatureCitations: [
      {
        title: 'Resting heart rate changes as an early indicator of post-surgical complications',
        source: 'Journal of Clinical Monitoring and Computing',
        year: 2023,
        relevanceScore: 0.81,
      },
      {
        title: 'Continuous vital sign monitoring after total knee arthroplasty',
        source: 'Orthopedic Nursing',
        year: 2022,
        relevanceScore: 0.77,
      },
    ],
    included: true,
    normalizationNote: 'Calculated as % change from pre-op resting HR; missing pre-op HR uses site median',
  },
];

export const MODEL_PROJECT: ModelProject = {
  name: 'TKA Complication Risk Model',
  targetVariable: 'post_op_complication_30d',
  population: 'Primary TKA patients, age ≥50',
  status: 'draft',
  eligibleCases: MODEL_COUNTS.eligibleCases,
  contributingSites: MODEL_COUNTS.sites,
  totalSites: MODEL_COUNTS.totalSites,
  featureCompleteness: MODEL_COUNTS.completeness,
  casesWithBiometrics: MODEL_COUNTS.withBiometrics,
  features: MODEL_FEATURES,
};
